config/routes.rb
Rails.application.routes.draw do
  resources :candidates
  resources :job_applications

  # CLEARANCE
  resources :passwords, controller: 'clearance/passwords', only: [:create, :new]
  resource :session, controller: 'clearance/sessions', only: [:create]
  resources :users, controller: 'clearance/users', only: [:create] do
    resource :password, controller: 'clearance/passwords', only: [:create, :edit, :update]
  end
  get '/sign_in' => 'sessions#new', as: 'sign_in'
  delete '/sign_out' => 'clearance/sessions#destroy', as: 'sign_out'
  get '/sign_up' => 'users#new', as: 'sign_up'
  get '/auth/google/callback' => 'sessions#auth_with_google', as: 'auth_with_google'
  # END OF CLEARANCE

  root 'job_applications#index'
end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  belongs_to :user
end

app/models/candidate.rb
class Candidate < ActiveRecord::Base
  has_many :job_applications

  def to_presenter
    CandidatePresenter.new(self)
  end

  def full_name
    "#{first_name.capitalize} #{last_name.upcase}".strip
  end

  def age
    return nil if year_of_birth.nil?
    Time.current.year - year_of_birth
  end
end

app/models/concerns/paperclipable.rb
module Paperclipable
  extend ActiveSupport::Concern

  include do
    before_post_process :skip_for_pdf
  end

  def skip_for_pdf
    ! %w(application/pdf).include?(file_upload_content_type)
  end
end

app/models/contract_type.rb
class ContractType < ActiveRecord::Base
  has_many :job_applications
end

app/models/job_application.rb
class JobApplication < ActiveRecord::Base
  include Paperclipable

  belongs_to :candidate
  accepts_nested_attributes_for :candidate, reject_if: :all_blank
  belongs_to :contract_type
  accepts_nested_attributes_for :contract_type, reject_if: :all_blank
  belongs_to :job_type
  accepts_nested_attributes_for :job_type, reject_if: :all_blank

  has_attached_file :cv
  validates_attachment_content_type :cv, content_type: ['image/jpeg', 'image/png', 'image/gif', 'application/pdf']

  def file_upload_content_type
    cv_content_type
  end

  def to_presenter
    JobApplicationPresenter.new(self)
  end
end

app/models/job_type.rb
class JobType < ActiveRecord::Base
  has_many :job_applications
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User

  has_many :authentications

  def self.create_with_password(params)
    password = generate_password
    params.merge!(password: password)
    User.create(params)
  end

  def self.generate_password
    rand(32**16).to_s(32)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  protect_from_forgery with: :exception
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  before_action :require_login

  def index
    @candidates = Candidate.all
  end

  def show
    find_candidate
  end

  def new
    @candidate = Candidate.new
  end

  def create
    @candidate = Candidate.new(candidate_params)
    if @candidate.save
      redirect_to candidate_path(@candidate)
    else
      render :new
    end
  end

  def edit
    find_candidate
  end

  def update
    find_candidate
    if @candidate.update_attributes(candidate_params)
      redirect_to candidate_path(@candidate)
    else
      render :edit
    end
  end

  def destroy
    find_candidate
    @candidate.destroy
    redirect_to candidates_path
  end

  private

  def candidate_params
    params.require(:candidate).permit(:first_name, :last_name, :email, :gender, :year_of_birth)
  end

  def find_candidate
    @candidate = Candidate.find(params[:id])
  end
end

app/controllers/job_applications_controller.rb
class JobApplicationsController < ApplicationController
  before_action :require_login

  def index
    @job_applications = JobApplication.all
  end

  def show
    find_job_application
  end

  def new
    @job_application = JobApplication.new
  end

  def create
    @job_application = JobApplication.new(job_application_params)
    if @job_application.save
      redirect_to job_application_path(@job_application)
    else
      render :new
    end
  end

  def edit
    find_job_application
  end

  def update
    find_job_application
    if @job_application.update_attributes(job_application_params)
      redirect_to job_application_path(@job_application)
    else
      render :edit
    end
  end

  private

  def job_application_params
    params.require(:job_application).permit(
      :received_at, :cv, :candidate_id, :contract_type_id, :job_type_id,
      contract_type_attributes: [:name],
      job_type_attributes: [:name],
      candidate_attributes: [:first_name, :last_name, :email, :gender, :year_of_birth]
    )
  end

  def find_job_application
    @job_application = JobApplication.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :require_login

  def home
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Clearance::SessionsController
  def new
    @google_auth_path = GoogleClient.new.auth_url
  end

  def auth_with_google
    user = find_user(request['code'])
    if user
      sign_in(user)
      notice = t('success.messages.google_auth')
    else
      notice = t('error.messages.google_auth')
    end
    redirect_to root_path, notice: notice
  end

  private

  def find_user(code)
    client = GoogleClient.new(code: code)
    return nil if client.code.nil?
    oauth_hash = client.fetch_access_token
    UserAuthentication.new(oauth_hash).auth!
  end
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController
  def new
    @google_auth_path = GoogleClient.new.auth_url
    super
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_controller(controller_name)
    params[:controller] == controller_name ? 'active' : nil
  end

  def active_action(action_name)
    params[:action] == action_name ? 'active' : nil
  end

  def active_li(text, path, class_attributes: '')
    class_name = current_page?(path) ? 'active' : ''
    class_attributes = "#{class_name} #{class_attributes}".strip
    content_tag(:li, class: class_attributes) do
      link_to text, path
    end
  end

  def present(model)
    klass = "#{model.class}Presenter".constantize
    presenter = klass.new(model)
    yield(presenter) if block_given?
  end
end

app/helpers/candidate_helper.rb
module CandidateHelper
  def gender_icon(g)
    case g
    when 'male'
      icon = 'fa fa-mars'
    when 'female'
      icon = 'fa fa-venus'
    end
    "<i class='#{icon}'></i>"
  end
end

app/views/candidates/_candidates_list.html.erb
<table class="footable table table-stripped toggle-arrow-tiny" data-page-size="15">
  <thead>
    <tr>
      <th><%= t('candidate.attributes.id') %></th>
      <th><%= t('candidate.attributes.full_name') %></th>
      <th data-hide="phone"><%= t('candidate.attributes.created_at') %></th>
      <th data-hide="phone"><%= t('candidate.attributes.updated_at') %></th>
      <th><%= t('status') %></th>
      <th class="text-right"><%= t('actions') %></th>
    </tr>
  </thead>
  <tbody>
    <% candidates.each do |candidate_object| %>
      <% present(candidate_object) do |candidate| %>
      <tr class='candidatesList-item'>
        <td><%= candidate.id %></td>
        <td><%= candidate.full_name %></td>
        <td><%= l candidate.created_at, format: :short %></td>
        <td><%= l candidate.updated_at, format: :short %></td>
        <td>
          <span class="label label-warning"><%= t('candidate.status.new') %></span>
        </td>
        <td class="text-right">
          <div class="btn-group">
            <%= link_to t('view'), candidate_path(candidate.id), class: 'btn-white btn btn-xs' %>
            <%= link_to t('edit'), edit_candidate_path(candidate.id), class: 'btn-white btn btn-xs' %>
            <%= link_to t('delete'), candidate_path(candidate.id), method: :delete, class: 'btn-white btn btn-xs', data: { confirm: t('candidate.messages.delete?') } %>
          </div>
        </td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <td colspan="7">
        <ul class="pagination pull-right"></ul>
      </td>
    </tr>
  </tfoot>
</table>

app/views/candidates/_details.html.erb
<div class="ibox float-e-margins">
  <div class="ibox-title">
    <h5><%= t('candidate.details') %></h5>
  </div>
  <div>
    <div class="ibox-content no-padding border-left-right">
      <!-- <img alt="image" class="img-responsive" src="img/profile_big.jpg"> -->
    </div>
    <div class="ibox-content profile-content">
      <h4><strong><%= candidate.full_name %></strong></h4>
      <p><i class="fa fa-envelope"></i> <%= candidate.email %></p>
      <p><i class="fa fa-birthday-cake"></i> <%= candidate.year_of_birth %></p>
      <p><%= raw gender_icon(candidate.gender) %> <%= candidate.gender %></p>
      <div class="user-button">
        <div class="row">
          <div class="col-md-6">
            <%= link_to edit_candidate_path(candidate.id), class: 'btn btn-default btn-sm btn-block' do %>
              <i class="fa fa-pencil-square-o"></i>
              <%= t('edit') %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/candidates/_form.html.erb
<%= form_for candidate, html: { class: 'form-horizontal' } do |f| %>
  <div class="form-group">
    <label class="col-sm-2 control-label"><%= t('candidates.attributes.full_name') %></label>
    <div class="row">
      <div class="col-sm-3">
        <%= f.text_field :first_name, class: 'form-control', placeholder: true %>
      </div>
      <div class="col-sm-3">
        <%= f.text_field :last_name, class: 'form-control', placeholder: true %>
      </div>
    </div>
  </div>
  <div class="hr-line-dashed"></div>
  <div class="form-group">
    <%= f.label :email, class: 'col-sm-2 control-label' %>
    <div class="col-sm-4">
      <div class="input-group m-b">
        <span class="input-group-addon">@</span>
        <%= f.text_field :email, class: 'form-control' %>
      </div>
    </div>
  </div>
  <div class="hr-line-dashed"></div>
  <div class="form-group">
    <%= f.label :gender, class: 'col-sm-2 control-label' %>
    <div class="col-sm-2">
      <div class="row">
        <div class="col-sm-6">
          <%= f.radio_button :gender, 'male', class: 'radio-primary' %>
          <%= f.label(:gender_male, t('candidate.gender.male')) %>
        </div>
        <div class="col-sm-6">
          <%= f.radio_button :gender, 'female', class: 'radio-primary' %>
          <%= f.label(:gender_female, t('candidate.gender.female')) %>
        </div>
      </div>
    </div>
  </div>
  <div class="hr-line-dashed"></div>
  <div class="form-group">
    <%= f.label :year_of_birth, class: 'col-sm-2 control-label' %>
    <div class="col-sm-4">
      <%= f.text_field :year_of_birth, class: 'form-control' %>
    </div>
  </div>
  <div class="hr-line-dashed"></div>
  <div class="form-group">
    <div class="col-sm-4 col-sm-offset-2">
      <%= link_to :back, class: 'btn btn-white' do %>
        <%= t('candidate.form.cancel') %>
      <% end %>
      <%= content_tag :button, type: :submit, class: 'btn btn-primary' do %>
        <%= t('candidate.form.save') %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/candidates/_no_results.html.erb
<div class="alert alert-info alert-dismissable">
  <%= t('candidate.messages.no_results') %>
</div>

app/views/candidates/_profil_detail.html.erb
<div class="ibox float-e-margins">
  <div class="ibox-title">
    <h5><%= t('candidate.detail') %></h5>
  </div>
  <div>
    <div class="ibox-content no-padding border-left-right">
      <!-- <img alt="image" class="img-responsive" src="img/profile_big.jpg"> -->
    </div>
    <div class="ibox-content profile-content">
      <h4><strong><%= candidate.full_name %></strong></h4>
      <p><i class="fa fa-envelope"></i> <%= candidate.email %></p>
      <p><i class="fa fa-birthday-cake"></i> <%= candidate.year_of_birth %></p>
      <p><%= raw gender_icon(candidate.gender) %> <%= candidate.gender %></p>
      <div class="user-button">
        <div class="row">
          <div class="col-md-6">
            <%= link_to edit_candidate_path(candidate.id), class: 'btn btn-default btn-sm btn-block' do %>
              <i class="fa fa-pencil-square-o"></i>
              <%= t('edit') %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/candidates/edit.html.erb
<% present(@candidate) do |candidate| %>
  <div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
      <h2><%= t('candidate.title.edit', name: candidate.full_name) %></h2>
    </div>
  </div>

  <div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
      <div class="col-lg-12">
        <div class="ibox float-e-margins">
          <div class="ibox-content">
            <%= render 'form', candidate: @candidate %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/candidates/index.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-10">
    <h2><%= "#{t('home.menu.candidates')} (#{@candidates.count})" %></h2>
  </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight ecommerce">
  <div class="row candidatesList">
    <div class="col-lg-12">
      <div class="ibox">
        <div class="ibox-title">
          <h5><%= t('candidate.index') %></h5>
          <div class="ibox-tools">
            <%= button_to new_candidate_path, class: 'btn btn-xs btn-primary', method: 'get' do %>
              <i class="fa fa-plus-square"></i>
              <%= t('candidate.messages.add') %>
            <% end %>
          </div>
        </div>
        <div class="ibox-content">
          <% if @candidates.count > 0 %>
            <%= render 'candidates_list', candidates: @candidates %>
          <% else %>
            <%= render 'no_results' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

</div>

<% content_for :javascript do %>

<script type="text/javascript">
  $(function() {
    $('.footable').footable();
  });
</script>

<% end %>

app/views/candidates/new.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-10">
    <h2><%= t('candidate.title.new') %></h2>
  </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox float-e-margins">
        <div class="ibox-content">
          <%= render 'form', candidate: @candidate %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/candidates/show.html.erb
<% present(@candidate) do |candidate| %>
  <div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
      <h2><%= t('candidate.title.show', name: candidate.full_name) %></h2>
    </div>
  </div>

  <div class="wrapper wrapper-content">
    <div class="row animated fadeInRight">
      <div class="col-md-4">
        <%= render 'details', candidate: candidate %>
      </div>
      <div class="col-md-8">
        <div class="ibox float-e-margins">
          <div class="ibox-title">
            <h5>Activites</h5>
          </div>
          <div class="ibox-content">
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/job_applications/_details.html.erb
<div class="ibox float-e-margins">
  <div class="ibox-title">
    <h5><%= t('job_applications.details') %></h5>
  </div>
  <div>
    <div class="ibox-content">
      <h4><strong><%= job_application.candidate_name %></strong></h4>
      <p>
        <i class="fa fa-birthday-cake"></i>
        <%= job_application.candidate_age %>
      </p>
      <p>
        <i class="fa fa-venus-mars"></i>
        <%= job_application.candidate_gender %>
      </p>
      <p>
        <i class="fa fa-envelope-o"></i>
        <%= job_application.candidate_email %>
      </p>
      <hr>
      <h5><strong><%= t('job_applications.received_at') %></strong></h5>
      <p><%= l job_application.received_at, format: :short_date %></p>
      <h5><strong><%= t('job_applications.contract_type_name') %></strong></h5>
      <p><%= job_application.contract_type.name %></p>
      <h5><strong><%= t('job_applications.job_type_name') %></strong></h5>
      <p><%= job_application.job_type.name %></p>
      <h5><strong><%= t('job_applications.cv') %></strong></h5>
      <p><%= link_to t('job_application.messages.link_to_cv_file'), job_application.cv_url, target: '_blank' %></p>
    </div>
  </div>
</div>

app/views/job_applications/_form.html.erb
<%= form_for job_application, html: { class: 'form-horizontal', multipart: true} do |f| %>
  <div class="form-group">
    <%= f.label :received_at, class: 'col-sm-2 control-label' %>
    <div class="col-sm-4">
      <div class="input-group date">
        <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
        <%= f.text_field :received_at, class: 'form-control', value: f.object.to_presenter.received_picker_date %>
      </div>
    </div>
  </div>
  <div class="hr-line-dashed"></div>
  <div class="form-group">
    <%= f.label :contract_type, class: 'col-sm-2 control-label' %>
    <div class="col-sm-6">
      <%= f.collection_select :contract_type_id, ContractType.all, :id, :name, {prompt: true},  { class: 'form-control m-b' } %>
      <p class="form-text-separation"><span><%= t('or_create') %></span></p>
      <%= f.fields_for :contract_type, job_application.build_contract_type do |contract_type| %>
        <%= contract_type.text_field :name, class: 'form-control', placeholder: t('contract_type.attributes.name') %>
      <% end %>
    </div>
  </div>
  <div class="hr-line-dashed"></div>
  <div class="form-group">
    <%= f.label :candidate, class: 'col-sm-2 control-label' %>
    <div class="col-sm-6">
      <%= f.collection_select :candidate_id, Candidate.all, :id, :full_name, {prompt: true},  { class: 'form-control m-b' } %>
      <p class="form-text-separation"><span><%= t('or_create') %></span></p>
      <%= f.fields_for :candidate, job_application.build_candidate do |candidate| %>
        <div class="row">
          <div class="col-sm-6">
            <%= candidate.text_field :first_name, class: 'form-control m-b', placeholder: t('candidate.attributes.first_name') %>
          </div>
          <div class="col-sm-6">
            <%= candidate.text_field :last_name, class: 'form-control m-b', placeholder: t('candidate.attributes.last_name') %>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-12">
            <div class="input-group m-b">
              <span class="input-group-addon"><i class="fa fa-envelope-o"></i></span>
              <%= candidate.text_field :email, class: 'form-control', placeholder: t('candidate.attributes.email') %>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-6">
            <div class="row">
              <div class="col-sm-6">
                <%= candidate.radio_button :gender, 'male', class: 'radio-primary' %>
                <%= candidate.label(:gender_male, t('candidate.gender.male')) %>
              </div>
              <div class="col-sm-6">
                <%= candidate.radio_button :gender, 'female', class: 'radio-primary' %>
                <%= candidate.label(:gender_female, t('candidate.gender.female')) %>
              </div>
            </div>
          </div>
          <div class="col-sm-6">
            <div class="input-group m-b">
              <span class="input-group-addon"><i class="fa fa-birthday-cake"></i></span>
              <%= candidate.text_field :year_of_birth, class: 'form-control', placeholder: t('candidate.attributes.year_of_birth') %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="hr-line-dashed"></div>
  <div class="form-group">
    <%= f.label :job_type, class: 'col-sm-2 control-label' %>
    <div class="col-sm-6">
      <%= f.collection_select :job_type_id, JobType.all, :id, :name, {prompt: true},  { class: 'form-control m-b' } %>
      <p class="form-text-separation"><span><%= t('or_create') %></span></p>
      <%= f.fields_for :job_type, job_application.build_job_type do |job_type| %>
        <%= job_type.text_field :name, class: 'form-control', placeholder: t('job_type.attributes.name') %>
      <% end %>
    </div>
  </div>
  <div class="hr-line-dashed"></div>
  <div class="form-group">
    <%= f.label :cv, class: 'col-sm-2 control-label' %>
    <div class="col-sm-6">
      <%= f.file_field :cv, class: 'form-control' %>
      <%= link_to t('job_application.messages.link_to_cv_file'), f.object.cv.url, target: '_blank' %>
    </div>
  </div>
  <div class="hr-line-dashed"></div>
  <div class="form-group">
    <div class="col-sm-4 col-sm-offset-2">
      <%= link_to :back, class: 'btn btn-white' do %>
        <%= t('job_application.form.cancel') %>
      <% end %>
      <%= content_tag :button, type: :submit, class: 'btn btn-primary' do %>
        <%= t('job_application.form.save') %>
      <% end %>
    </div>
  </div>
<% end %>

<%= content_for :javascript do %>

<script type="text/javascript">
  $(document).ready(function(){
    $('#job_application_received_at').datepicker({
      todayBtn: 'linked',
      keyboardNavigation: false,
      forceParse: false,
      calendarWeeks: true,
      autoclose: true,
      language: '<%= I18n.locale %>',
      format: 'dd/mm/yyyy'
    });
  });
</script>

<% end %>

app/views/job_applications/_job_applications_list.html.erb
<table class="footable table table-stripped toggle-arrow-tiny" data-page-size="15">
  <thead>
    <tr>
      <th><%= t('job_application.attributes.received_at') %></th>
      <th><%= t('job_application.attributes.candidate') %></th>
      <th><%= t('job_application.attributes.contract_type.name') %></th>
      <th><%= t('job_application.attributes.job_type.name') %></th>
      <th><%= t('job_application.attributes.cv') %></th>
      <th data-hide="phone"><%= t('job_application.attributes.created_at') %></th>
      <th data-hide="phone"><%= t('job_application.attributes.updated_at') %></th>
      <th class="text-right"><%= t('actions') %></th>
    </tr>
  </thead>
  <tbody>
    <% job_applications.each do |job_application_object| %>
      <% present(job_application_object) do |job_application| %>
      <tr class='job_applicationsList-item'>
        <td><%= job_application.received_date %></td>
        <td><%= job_application.candidate_link %></td>
        <td>
          <span class="label label-warning"><%= job_application.contract_name %></span>
        </td>
        <td><%= job_application.job_name %></td>
        <td><%= link_to t('job_application.messages.link_to_cv_file'), job_application.cv_url %></td>
        <td><%= l job_application.created_at, format: :short %></td>
        <td><%= l job_application.updated_at, format: :short %></td>
        <td class="text-right">
          <div class="btn-group">
            <%= link_to t('view'), job_application_path(job_application.id), class: 'btn-white btn btn-xs' %>
            <%= link_to t('edit'), edit_job_application_path(job_application.id), class: 'btn-white btn btn-xs' %>
            <%= link_to t('delete'), job_application_path(job_application.id), method: :delete, class: 'btn-white btn btn-xs', data: { confirm: t('job_application.messages.delete?') } %>
          </div>
        </td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <td colspan="7">
        <ul class="pagination pull-right"></ul>
      </td>
    </tr>
  </tfoot>
</table>

app/views/job_applications/_no_results.html.erb
<div class="alert alert-info alert-dismissable">
  <%= t('job_application.messages.no_results') %>
</div>

app/views/job_applications/index.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-10">
    <h2><%= "#{t('home.menu.job_applications')} (#{@job_applications.count})" %></h2>
  </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight ecommerce">
  <div class="row job_applicationsList">
    <div class="col-lg-12">
      <div class="ibox">
        <div class="ibox-title">
          <h5><%= t('job_application.index') %></h5>
          <div class="ibox-tools">
            <%= button_to new_job_application_path, class: 'btn btn-xs btn-primary', method: 'get' do %>
              <i class="fa fa-plus-square"></i>
              <%= t('job_application.messages.add') %>
            <% end %>
          </div>
        </div>
        <div class="ibox-content">
          <% if @job_applications.count > 0 %>
            <%= render 'job_applications_list', job_applications: @job_applications %>
          <% else %>
            <%= render 'no_results' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

</div>

<% content_for :javascript do %>

<script type="text/javascript">
  $(function() {
    $('.footable').footable();
  });
</script>

<% end %>

app/views/job_applications/show.html.erb
<% present(@job_application) do |job_application| %>
  <div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
      <h2><%= t('job_application.title.show', time: job_application.received_date) %></h2>
    </div>
    <div class="col-lg-2">
      <%= link_to t('edit'), edit_job_application_path(@job_application), class: 'btn btn-w-m btn-white space-20 pull-right' %>
    </div>
  </div>

  <div class="wrapper wrapper-content">
    <div class="row animated fadeInRight">
      <div class="col-md-4">
        <%= render 'details', job_application: job_application %>
      </div>
      <div class="col-md-8">
        <div class="ibox float-e-margins">
          <div class="ibox-title">
            <h5>Activites</h5>
          </div>
          <div class="ibox-content">
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="pull-right">
    Example text
  </div>
  <div>
    <strong>Copyright</strong> Example Company &copy; 2014-2015
  </div>
</div>

app/views/layouts/_topnavbar.html.erb
<div class="row border-bottom white-bg">
  <nav class="navbar navbar-static-top" role="navigation">
    <div class="navbar-header">
      <button aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" class="navbar-toggle collapsed" type="button">
        <i class="fa fa-reorder"></i>
      </button>
      <%= link_to 'HRM', root_path, class: 'navbar-brand' %>
    </div>
    <div class="navbar-collapse collapse" id="navbar">
      <ul class="nav navbar-nav">
        <%= active_li(t('home.menu.job_applications'), job_applications_path) %>
        <%= active_li(t('home.menu.candidates'), candidates_path) %>
      </ul>
      <ul class="nav navbar-top-links navbar-right">
        <% if signed_in? %>
          <li>
            <%= link_to current_user.email, '#' %>
          </li>
          <li>
            <%= render 'shared/sign_out' %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
</div>

app/views/pages/home.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-10">
    <h2>Home</h2>
  </div>
</div>

app/views/shared/_sign_out.html.erb
<%= button_to sign_out_path, method: :delete, class: 'btn btn-primary' do %>
  <i class="fa fa-sign-out"></i> <%= t '.sign_out' %>
<% end %>

app/views/users/new.html.erb
<div class="middle-box text-center loginscreen   animated fadeInDown">
  <div>
    <h3>Register to IN+</h3>
    <p>Create account to see it in action.</p>
    <%= form_for @user, class:'m-t' do |form| %>
      <%= render '/users/form', form: form %>
      <div class="form-group">
        <div class="checkbox"><label> <input type="checkbox"><i></i> Agree the terms and policy </label></div>
      </div>
      <%= form.button t('.new_user'), class: 'btn btn-primary block full-width m-b', type: 'submit' %>
      <%= render 'shared/google_connect', path: @google_auth_path %>
      <div class="other-links">
        <p class="text-muted text-center"><small><%= t('.has_account') %></small></p>
        <%= link_to t(".sign_in"), sign_in_path, class: 'btn btn-sm btn-white btn-block' %>
      </div>
    <% end %>
    <p class="m-t"> <small>Inspinia we app framework base on Bootstrap 3 &copy; 2014</small> </p>
  </div>
</div>